-- Seed sample news articles
INSERT OR IGNORE INTO news_articles (id, title, summary, content, url, imageUrl, sourceId, category, tags, publishedAt, relevanceScore, isBreaking, isFeatured, viewCount) VALUES
  ('art_001', 'Government Launches Digital Ghana Agenda Phase 2', 'President announces the next phase of the Digital Ghana Agenda, focusing on public sector digitization and e-governance initiatives across all MDAs.', NULL, 'https://gna.org.gh/article/digital-ghana-phase-2', 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800', 'src_gna', 'technology', '["digital transformation", "e-governance", "technology"]', datetime('now', '-1 hours'), 98, 1, 1, 245),

  ('art_002', 'New Public Service Training Initiative for Civil Servants', 'OHCS announces comprehensive training program for civil servants focusing on digital skills, leadership, and public administration excellence.', NULL, 'https://graphic.com.gh/article/training-initiative', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800', 'src_graphic', 'training', '["training", "capacity building", "civil service"]', datetime('now', '-3 hours'), 95, 0, 0, 178),

  ('art_003', 'Budget 2025: Focus on Public Sector Reform', 'Finance Minister presents 2025 budget with significant allocations for public sector reforms, digitization, and civil service restructuring.', NULL, 'https://myjoyonline.com/article/budget-2025', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800', 'src_myjoy', 'policy', '["budget", "public sector", "reform", "finance"]', datetime('now', '-5 hours'), 92, 0, 0, 312),

  ('art_004', 'Civil Service Performance Awards Ceremony Announced', 'Annual Civil Service Performance Awards to recognize outstanding civil servants across all MDAs. Nominations now open.', NULL, 'https://citinewsroom.com/article/performance-awards', 'https://images.unsplash.com/photo-1569098644016-e87b1c1b8fbd?w=800', 'src_citinews', 'announcements', '["awards", "performance", "civil service", "recognition"]', datetime('now', '-8 hours'), 85, 0, 0, 156),

  ('art_005', 'Health Ministry Implements New Policy on Remote Work', 'Ministry of Health becomes first MDA to fully implement hybrid work policy, allowing eligible staff to work remotely three days per week.', NULL, 'https://ghanaweb.com/article/health-remote-work', 'https://images.unsplash.com/photo-1585974738771-84483dd9f89f?w=800', 'src_ghanaweb', 'hr', '["remote work", "health ministry", "policy", "hybrid work"]', datetime('now', '-12 hours'), 88, 0, 0, 423),

  ('art_006', 'Ghana Signs Agreement on Regional e-Government Cooperation', 'Ghana leads ECOWAS initiative on shared e-government platforms and regional digital cooperation framework.', NULL, 'https://gna.org.gh/article/ecowas-e-government', 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800', 'src_gna', 'policy', '["ECOWAS", "e-government", "regional cooperation", "digital"]', datetime('now', '-24 hours'), 82, 0, 0, 198),

  ('art_007', 'New Pension Scheme Benefits for Civil Servants', 'SSNIT announces enhanced pension benefits for civil servants, including improved retirement packages and healthcare coverage.', NULL, 'https://peacefmonline.com/article/pension-benefits', 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800', 'src_peacefm', 'hr', '["pension", "SSNIT", "benefits", "retirement"]', datetime('now', '-36 hours'), 90, 0, 0, 267),

  ('art_008', 'Anti-Corruption Training Mandatory for All Civil Servants', 'Office of the Special Prosecutor announces mandatory anti-corruption awareness training for all civil servants starting next month.', NULL, 'https://gna.org.gh/article/anti-corruption-training', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800', 'src_gna', 'training', '["anti-corruption", "training", "governance", "ethics"]', datetime('now', '-48 hours'), 94, 0, 0, 389),

  ('art_009', 'Public Services Commission Releases 2025 Recruitment Guidelines', 'New guidelines outline transparent and merit-based recruitment process for civil service positions across all levels.', NULL, 'https://graphic.com.gh/article/recruitment-guidelines', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800', 'src_graphic', 'announcements', '["recruitment", "guidelines", "civil service", "employment"]', datetime('now', '-60 hours'), 87, 1, 0, 512),

  ('art_010', 'OHCS Launches E-Library Platform for Knowledge Sharing', 'The Office of the Head of Civil Service unveils new digital library platform to enhance knowledge sharing and professional development among civil servants.', NULL, 'https://gna.org.gh/article/ohcs-elibrary', 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800', 'src_gna', 'technology', '["e-library", "knowledge management", "digital platform", "OHCS"]', datetime('now', '-72 hours'), 96, 0, 1, 634);
